[2023-06-09T23:41:06.835+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: custom_operator.hello manual__2023-06-09T23:41:05.567528+00:00 [queued]>
[2023-06-09T23:41:06.844+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: custom_operator.hello manual__2023-06-09T23:41:05.567528+00:00 [queued]>
[2023-06-09T23:41:06.844+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-09T23:41:06.855+0000] {taskinstance.py:1327} INFO - Executing <Task(HelloOperator): hello> on 2023-06-09 23:41:05.567528+00:00
[2023-06-09T23:41:06.861+0000] {standard_task_runner.py:57} INFO - Started process 12574 to run task
[2023-06-09T23:41:06.873+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'custom_operator', 'hello', 'manual__2023-06-09T23:41:05.567528+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/4_custom_operator.py', '--cfg-path', '/tmp/tmp9gjdgfqb']
[2023-06-09T23:41:06.878+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask hello
[2023-06-09T23:41:06.993+0000] {task_command.py:410} INFO - Running <TaskInstance: custom_operator.hello manual__2023-06-09T23:41:05.567528+00:00 [running]> on host 5fef267ae46d
[2023-06-09T23:41:07.074+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='custom_operator' AIRFLOW_CTX_TASK_ID='hello' AIRFLOW_CTX_EXECUTION_DATE='2023-06-09T23:41:05.567528+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-09T23:41:05.567528+00:00'
[2023-06-09T23:41:07.075+0000] {taskinstance.py:1824} ERROR - Task failed with exception
TypeError: execute() got an unexpected keyword argument 'context'
[2023-06-09T23:41:07.087+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=custom_operator, task_id=hello, execution_date=20230609T234105, start_date=20230609T234106, end_date=20230609T234107
[2023-06-09T23:41:07.109+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 20 for task hello (execute() got an unexpected keyword argument 'context'; 12574)
[2023-06-09T23:41:07.164+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-09T23:41:07.181+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
